version: '3'

services:
  postgres:
    container_name: test_idx_db
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: clients
      POSTGRES_PASSWORD: clients
      POSTGRES_DB: clients
    volumes:
      - ~/storage/test_idx/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - test_idx

  rabbitmq:
    container_name: test_idx_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - ~/storage/test_idx/rabbitmq:/var/lib/rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    networks:
      - test_idx

  elasticsearch:
    image: elasticsearch:7.13.4
    container_name: test_idx_elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/storage/test_idx/elasticsearch:/data/db
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - test_idx

networks:
  test_idx:
    driver: bridge